export const SET_MOVIES = "SET_MOVIES";
export const RESET_MOVIES = "RESET_MOVIES";
export const SELECT_MOVIE = "SELECT_MOVIE";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
export const SEARCH_MOVIES = "SEARCH_MOVIES";